# Python , Numpy and Vectorization

In [2]:
import numpy as np
import time

## Vector Creation

In [ ]:
a = np.zeros(4)
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,))
print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4)
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

In [ ]:
a = np.arange(4.)           
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4)         
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

# Indexing
Indexing means referring to an element of an array by its position within the array.

NumPy starts indexing at zero so the 3rd element of an vector  𝐚
  is a[2].

In [ ]:
a = np.arange(10)
print(a)

# access an element
print(f"a[2].shape : {a[2].shape} a[2]= {a[2]}")

# access an element with a negative index

print(f"a[-1]= {a[-1]}")

# indexes must be within the range of the vector or they will produce an error

try:
    print(a[10])
except Exception as e:
    print("The error message you will see is: ")
    print(e)

### 3.4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [ ]:
a = np.arange(10)
print(f" a = {a}")

# access 5 consecutive elements
print(f"a[1,6,1] = {a[1:6:1]}")

# access 3 elements separted by 2
c = a[2:7:2]
print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:]
print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3]
print("a[:3]    = ", c)

# access all elements
c = a[:]
print("a[:]     = ", c)

 a = [0 1 2 3 4 5 6 7 8 9]
a[1,6,1] = [1 2 3 4 5]


## Single Vector Operations

In [ ]:
a = np.array([1,2,3,4])

b = -a
print(b)

# sum
# sum all the elements in the array and returns a scalar
c = np.sum(a)
print(c)

# mean

d = np.mean(a)
print(d)

# power

e = a **2
print(e)

## Vector Vector element wise operations

In [20]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise {a + b}")

Binary operators work element wise [0 0 6 8]


## Scalar vector operations

In [21]:
a = np.array([1,2,3,4])
b = a * 5
print(b)

[ 5 10 15 20]


## Vector dot Product

In [22]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


## The need for Speed : Vector Vs loop

In [24]:
np.random.seed(1)
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
start = time.time()
c = np.dot(a,b)
end = time.time()
print(f"Total time taken by vectorization: {end-start:.4f}")

start = time.time()
total = 0
for i in range(1000000):
    c = a[i]*b[i]
    total+=c
end = time.time()
print(f"Total time taken by loop = {end - start:.4f}")

Total time taken by vectorization: 0.0032
Total time taken by loop = 1.5898


## Vector Vector operations

In [ ]:
# show common Course 1 example
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)
print(w)
print(c)
print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

## Matrix Creation

In [ ]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

In [ ]:
a = np.array([[5], [4], [3]])
print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

## Matrix Indexing

In [ ]:
#vector indexing operations on matrices
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

#access an element
print(f"\na[2,0].shape:   {a[2, 0].shape}, a[2,0] = {a[2, 0]},     type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

#access a row
print(f"a[2].shape:   {a[2].shape}, a[2]   = {a[2]}, type(a[2])   = {type(a[2])}")

## Slicing


In [32]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
